version: '3'
services:
    docker-node-network-mongo:
        build: .
        ports:
        - "8080:8080"
        networks:
        - mongo-net
    mongodev:
        image: mongo
        ports:
        - "27017:27017"
        networks:
        - mongo-net
networks:
    mongo-net:
        driver: bridge